import { Platform } from 'react-native';

/**
 * Register the PWA service worker (dist/sw.js, generated by `npm run build:pwa`).
 * Production web only: the Metro dev server doesn't serve sw.js, and caching
 * would interfere with live preview anyway.
 *
 * The worker precaches the JS bundle, so without the update handling below a
 * published fix can keep showing the previous build to anyone who already
 * opened the site. `skipWaiting` + `clientsClaim` (workbox-config.js) make a new
 * worker take control immediately; this reloads the page once that happens so
 * the tab actually runs the new bundle.
 */
export function registerServiceWorker(): void {
  if (Platform.OS !== 'web' || typeof window === 'undefined') return;
  if (process.env.NODE_ENV !== 'production') return;
  if (!('serviceWorker' in navigator)) return;

  let reloading = false;
  const hadController = navigator.serviceWorker.controller !== null;

  navigator.serviceWorker.addEventListener('controllerchange', () => {
    // First install has no previous controller — nothing stale to replace.
    if (!hadController || reloading) return;
    reloading = true;
    window.location.reload();
  });

  window.addEventListener('load', () => {
    navigator.serviceWorker
      .register('/sw.js')
      .then((registration) => {
        void registration.update();

        // A tab left open for days would otherwise never notice a new release.
        const checkForUpdate = () => {
          if (document.visibilityState === 'visible') void registration.update();
        };
        document.addEventListener('visibilitychange', checkForUpdate);
      })
      .catch(() => {
        // Registration is best-effort; the app works without offline support.
      });
  });
}
